name: "GitHub Actions for CDK"

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read

jobs:
  deploy-cdk:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup dependencies for CDK
        run: npm ci

      - name: Bootstrap CDK
        run: npx cdk bootstrap

      - name: Build CDK
        run: npm run build

      - name: CDK Diff Check
        run: npx cdk diff

      - name: CDK Deploy
        # run: npx cdk deploy --require-approval never --all
        run: npx cdk deploy --require-approval always

  # notify-slack-success:
  #   runs-on: ubuntu-latest
  #   needs: deploy-cdk
  #   if: ${{ success() }}
  #   steps:
  #     - name: Slack Notification - Success
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_CHANNEL: github-channel
  #         SLACK_USERNAME: rtCamp
  #         SLACK_ICON: https://github.com/rtCamp.png?size=48
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         SLACK_COLOR: "good"
  #         SLACK_TITLE: "✅ Deployment Succeeded"
  #         SLACK_MESSAGE: |
  #           The CDK deployment has succeeded for branch *${{ github.ref_name }}*.
  #           *Committer:* ${{ github.actor }}
  #           *Workflow Run:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Details>

  # notify-slack-failure:
  #   runs-on: ubuntu-latest
  #   needs: deploy-cdk
  #   if: ${{ failure() }}
  #   steps:
  #     - name: Slack Notification - Failure
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_CHANNEL: github-channel
  #         SLACK_USERNAME: rtCamp
  #         SLACK_ICON: https://github.com/rtCamp.png?size=48
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         SLACK_COLOR: "danger"
  #         SLACK_TITLE: "❌ Deployment Failed"
  #         SLACK_MESSAGE: |
  #           The CDK deployment has failed for branch *${{ github.ref_name }}*.
  #           *Committer:* ${{ github.actor }}
  #           *Workflow Run:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Details>
