name: "CI/CD for CDK"

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read

jobs:
  deploy-cdk:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup dependencies for CDK
        run: npm ci

      - name: Bootstrap CDK
        run: npx cdk bootstrap

      - name: Build CDK
        run: npm run build

      - name: CDK Diff Check
        run: npx cdk diff

      - name: CDK Deploy
        run: npx cdk deploy --require-approval never --all

      # Slack通知（成功時）
      - name: Notify Slack on success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          payload: |
            {
              "text": "✅ GitHub Actions Workflow '{{ github.workflow }}' succeeded in repository '{{ github.repository }}' on branch '{{ github.ref_name }}'.",
              "attachments": [
                {
                  "text": "View details: {{ github.server_url }}/{{ github.repository }}/actions/runs/{{ github.run_id }}"
                }
              ]
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

      # Slack通知（失敗時）
      - name: Notify Slack on failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          payload: |
            {
              "text": "❌ GitHub Actions Workflow '{{ github.workflow }}' failed in repository '{{ github.repository }}' on branch '{{ github.ref_name }}'.",
              "attachments": [
                {
                  "text": "View details: {{ github.server_url }}/{{ github.repository }}/actions/runs/{{ github.run_id }}"
                }
              ]
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
